[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  ASTRO_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://cro-cafe.netlify.app/*"
  to = "https://www.cro.cafe/:splat"
  status = 301
  force = true

# Language redirects
[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/"
  to = "/nl"
  status = 302
  conditions = {Language = ["nl"]}

[[redirects]]
  from = "/"
  to = "/es"
  status = 302
  conditions = {Language = ["es"]}

# 404 handling
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
