name: Sync Episodes

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run sync script
        id: sync
        continue-on-error: true
        env:
          TRANSISTOR_API_KEY: ${{ secrets.TRANSISTOR_API_KEY }}
        run: npm run sync-episodes
      
      - name: Check sync status
        if: steps.sync.outcome != 'success'
        run: |
          echo "::error::Episode sync failed"
          exit 1
      
      - name: Check for changes
        id: git-check
        if: steps.sync.outcome == 'success'
        run: |
          git add src/content/*-episodes/
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT
      
      - name: Commit and push if changes
        if: steps.sync.outcome == 'success' && steps.git-check.outputs.changes > 0
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update episodes from Transistor API"
          git push

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Episode Sync Failed',
              body: `The episode sync workflow failed at ${new Date().toISOString()}.
              
              [View workflow run](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})
              
              Please check the workflow logs for more details.`,
              labels: ['sync-failure', 'bug']
            });
            
            console.log(`Created issue #${issue.data.number}`);
