name: Sync Episodes

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual trigger
  repository_dispatch:
    types: [transistor-webhook]  # Triggered by webhook

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      TRANSISTOR_API_KEY: ${{ secrets.TRANSISTOR_API_KEY }}
    
    steps:
      - name: Check required secrets
        run: |
          if [ -z "$TRANSISTOR_API_KEY" ]; then
            echo "Error: TRANSISTOR_API_KEY secret is not set"
            exit 1
          fi
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create .env file
        run: |
          echo "TRANSISTOR_API_KEY=${{ secrets.TRANSISTOR_API_KEY }}" > .env

      - name: Verify .env file
        run: |
          if [ ! -f .env ]; then
            echo "Error: .env file was not created"
            exit 1
          fi
          if ! grep -q "TRANSISTOR_API_KEY=" .env; then
            echo "Error: TRANSISTOR_API_KEY is missing from .env"
            exit 1
          fi
          echo "✓ .env file exists and contains TRANSISTOR_API_KEY"

      - name: Sync episodes and download images
        run: |
          npm run sync-episodes
          npm run download-images
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/content/*-episodes/ public/images/episodes/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update episodes and images from Transistor"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
