name: Sync Episodes

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual trigger
  repository_dispatch:
    types: [transistor-webhook]  # Triggered by webhook

# Add explicit permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper pushing
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Debug environment
        run: |
          echo "Checking if TRANSISTOR_API_KEY is set (should show 'true')"
          if [ -n "$TRANSISTOR_API_KEY" ]; then echo "true"; else echo "false"; fi
          echo "First few characters of the key:"
          echo "${TRANSISTOR_API_KEY:0:4}..."
          echo "Checking GitHub secrets:"
          echo "TRANSISTOR_API_KEY secret exists: ${{ secrets.TRANSISTOR_API_KEY != '' }}"
        env:
          TRANSISTOR_API_KEY: ${{ secrets.TRANSISTOR_API_KEY }}

      - name: Sync episodes and download images
        run: |
          # Print Node.js environment variables
          echo "Checking Node.js environment:"
          node -e "console.log('TRANSISTOR_API_KEY set:', !!process.env.TRANSISTOR_API_KEY)"
          node -e "if(process.env.TRANSISTOR_API_KEY) console.log('First few chars:', process.env.TRANSISTOR_API_KEY.substring(0, 4) + '...')"
          
          # Run sync-episodes with API key as command-line argument
          npx tsx scripts/sync-episodes.ts --api-key "$TRANSISTOR_API_KEY"
          
          # Run download-images (doesn't need API key)
          npm run download-images
        env:
          TRANSISTOR_API_KEY: ${{ secrets.TRANSISTOR_API_KEY }}
      
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/content/*-episodes/ public/images/episodes/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update episodes and images from Transistor"
      
      - name: Push changes
        run: git push
